import type { TonalParams } from './dsp/types'

export type TonalPresetKey =
  | 'laser'
  | 'coin'
  | 'beep'
  | 'jump'
  | 'whoosh'
  | 'magic'
  | 'electric'

// Same RangeFor pattern as v1's percussive presets — numeric params get
// [min, max], categorical params get readonly arrays. The [T] tuple wrap
// prevents distribution over union types.
type RangeFor<T> = [T] extends [number] ? [number, number] : readonly T[]

export interface TonalPresetDefinition {
  key: TonalPresetKey
  name: string
  description: string
  defaults: TonalParams
  ranges: {
    [K in keyof TonalParams]?: RangeFor<TonalParams[K]>
  }
}

export const TONAL_PRESETS: Record<TonalPresetKey, TonalPresetDefinition> = {
  laser: {
    key: 'laser',
    name: 'Laser',
    description:
      'Pitch-sweep aggressive sound — square+saw with downward sweep. The classic.',
    defaults: {
      base_pitch_semitones: 0,
      osc_a_wave: 'square',
      osc_a_level: 0.8,
      osc_b_wave: 'saw',
      osc_b_level: 0.6,
      osc_b_detune_cents: 8,
      sub_amount: 0.0,
      noise_type: 'white',
      noise_amount: 0.1,
      filter_type: 'lowpass',
      filter_freq_hz: 4000,
      filter_q: 4,
      filter_env_amount: -0.5,
      filter_env_attack_ms: 8,
      filter_env_decay_ms: 200,
      amp_attack_ms: 2,
      amp_decay_ms: 100,
      amp_sustain: 0.0,
      amp_release_ms: 150,
      pitch_env_amount_oct: -1.5,
      pitch_env_attack_ms: 8,
      pitch_env_decay_ms: 180,
      lfo_rate_hz: 5,
      lfo_depth: 0.0,
      lfo_shape: 'sine',
      lfo_target: 'off',
      gain: 0.85,
    },
    ranges: {
      base_pitch_semitones: [-6, 6],
      osc_a_wave: ['square', 'saw'],
      osc_a_level: [0.6, 1.0],
      osc_b_wave: ['square', 'saw', 'sine'],
      osc_b_level: [0.3, 0.8],
      osc_b_detune_cents: [0, 25],
      sub_amount: [0.0, 0.4],
      noise_type: ['white', 'pink'],
      noise_amount: [0.0, 0.25],
      filter_type: ['lowpass', 'bandpass'],
      filter_freq_hz: [2000, 8000],
      filter_q: [2, 8],
      filter_env_amount: [-0.8, -0.2],
      filter_env_attack_ms: [5, 15],
      filter_env_decay_ms: [100, 400],
      amp_attack_ms: [0, 8],
      amp_decay_ms: [50, 200],
      amp_sustain: [0.0, 0.2],
      amp_release_ms: [80, 300],
      pitch_env_amount_oct: [-2.0, -0.8],
      pitch_env_attack_ms: [5, 20],
      pitch_env_decay_ms: [100, 350],
      lfo_target: ['off', 'pitch'],
      lfo_depth: [0.0, 0.3],
      gain: [0.75, 0.95],
    },
  },

  coin: {
    key: 'coin',
    name: 'Coin',
    description: 'Bright pickup with tonal ring — triangle+sine, holds for ring.',
    defaults: {
      base_pitch_semitones: 0,
      osc_a_wave: 'triangle',
      osc_a_level: 0.9,
      osc_b_wave: 'sine',
      osc_b_level: 0.4,
      osc_b_detune_cents: 5,
      sub_amount: 0.0,
      noise_type: 'none',
      noise_amount: 0.0,
      filter_type: 'lowpass',
      filter_freq_hz: 6000,
      filter_q: 1.5,
      filter_env_amount: 0.0,
      filter_env_attack_ms: 0,
      filter_env_decay_ms: 100,
      amp_attack_ms: 5,
      amp_decay_ms: 60,
      amp_sustain: 0.6,
      amp_release_ms: 250,
      pitch_env_amount_oct: 0.0,
      pitch_env_attack_ms: 0,
      pitch_env_decay_ms: 50,
      lfo_rate_hz: 4,
      lfo_depth: 0.0,
      lfo_shape: 'sine',
      lfo_target: 'off',
      gain: 0.75,
    },
    ranges: {
      base_pitch_semitones: [-12, 12],
      osc_a_wave: ['sine', 'triangle'],
      osc_a_level: [0.7, 1.0],
      osc_b_wave: ['sine', 'triangle'],
      osc_b_level: [0.2, 0.7],
      osc_b_detune_cents: [0, 15],
      sub_amount: [0.0, 0.3],
      filter_freq_hz: [4000, 9000],
      filter_q: [0.7, 3],
      filter_env_amount: [-0.2, 0.2],
      filter_env_decay_ms: [50, 200],
      amp_attack_ms: [1, 15],
      amp_decay_ms: [30, 100],
      amp_sustain: [0.4, 0.8],
      amp_release_ms: [150, 450],
      pitch_env_amount_oct: [-0.1, 0.1],
      pitch_env_decay_ms: [30, 100],
      lfo_depth: [0.0, 0.2],
      gain: [0.65, 0.9],
    },
  },

  beep: {
    key: 'beep',
    name: 'Beep',
    description: 'Simple UI confirmation — sine, brief, fixed pitch. Minimal preset.',
    defaults: {
      base_pitch_semitones: 0,
      osc_a_wave: 'sine',
      osc_a_level: 1.0,
      osc_b_wave: 'sine',
      osc_b_level: 0.0,
      osc_b_detune_cents: 0,
      sub_amount: 0.0,
      noise_type: 'none',
      noise_amount: 0.0,
      filter_type: 'lowpass',
      filter_freq_hz: 8000,
      filter_q: 0.7,
      filter_env_amount: 0.0,
      filter_env_attack_ms: 0,
      filter_env_decay_ms: 50,
      amp_attack_ms: 3,
      amp_decay_ms: 30,
      amp_sustain: 0.7,
      amp_release_ms: 80,
      pitch_env_amount_oct: 0,
      pitch_env_attack_ms: 0,
      pitch_env_decay_ms: 50,
      lfo_rate_hz: 4,
      lfo_depth: 0.0,
      lfo_shape: 'sine',
      lfo_target: 'off',
      gain: 0.7,
    },
    ranges: {
      base_pitch_semitones: [-12, 12],
      osc_a_wave: ['sine', 'triangle'],
      osc_a_level: [0.8, 1.0],
      osc_b_level: [0.0, 0.2],
      osc_b_detune_cents: [0, 8],
      filter_freq_hz: [5000, 12000],
      filter_q: [0.5, 1.5],
      amp_attack_ms: [1, 8],
      amp_decay_ms: [15, 60],
      amp_sustain: [0.5, 0.9],
      amp_release_ms: [40, 150],
      lfo_depth: [0.0, 0.2],
      gain: [0.6, 0.85],
    },
  },

  jump: {
    key: 'jump',
    name: 'Jump',
    description: 'Upward pitch sweep with quick decay — platformer staple.',
    defaults: {
      base_pitch_semitones: 0,
      osc_a_wave: 'square',
      osc_a_level: 0.9,
      osc_b_wave: 'triangle',
      osc_b_level: 0.4,
      osc_b_detune_cents: 6,
      sub_amount: 0.1,
      noise_type: 'none',
      noise_amount: 0.0,
      filter_type: 'lowpass',
      filter_freq_hz: 5500,
      filter_q: 2,
      filter_env_amount: 0.2,
      filter_env_attack_ms: 5,
      filter_env_decay_ms: 150,
      amp_attack_ms: 4,
      amp_decay_ms: 80,
      amp_sustain: 0.0,
      amp_release_ms: 150,
      pitch_env_amount_oct: 1.2,
      pitch_env_attack_ms: 80,
      pitch_env_decay_ms: 100,
      lfo_rate_hz: 4,
      lfo_depth: 0.0,
      lfo_shape: 'sine',
      lfo_target: 'off',
      gain: 0.8,
    },
    ranges: {
      base_pitch_semitones: [-6, 6],
      osc_a_wave: ['square', 'triangle'],
      osc_a_level: [0.7, 1.0],
      osc_b_wave: ['square', 'triangle'],
      osc_b_level: [0.2, 0.6],
      osc_b_detune_cents: [0, 18],
      sub_amount: [0.0, 0.4],
      filter_type: ['lowpass', 'bandpass'],
      filter_freq_hz: [3000, 9000],
      filter_q: [1, 4],
      filter_env_amount: [-0.2, 0.5],
      filter_env_attack_ms: [0, 20],
      filter_env_decay_ms: [80, 250],
      amp_attack_ms: [1, 12],
      amp_decay_ms: [40, 150],
      amp_sustain: [0.0, 0.3],
      amp_release_ms: [80, 280],
      pitch_env_amount_oct: [0.6, 1.8],
      pitch_env_attack_ms: [40, 150],
      pitch_env_decay_ms: [50, 200],
      lfo_depth: [0.0, 0.2],
      gain: [0.7, 0.9],
    },
  },

  whoosh: {
    key: 'whoosh',
    name: 'Whoosh',
    description: 'Noise-dominated swept sound — BP filter sweep on noise.',
    defaults: {
      base_pitch_semitones: 0,
      osc_a_wave: 'sine',
      osc_a_level: 0.05,
      osc_b_wave: 'sine',
      osc_b_level: 0.0,
      osc_b_detune_cents: 0,
      sub_amount: 0.0,
      noise_type: 'pink',
      noise_amount: 0.9,
      filter_type: 'bandpass',
      filter_freq_hz: 1500,
      filter_q: 6,
      filter_env_amount: 0.6,
      filter_env_attack_ms: 80,
      filter_env_decay_ms: 250,
      amp_attack_ms: 50,
      amp_decay_ms: 100,
      amp_sustain: 0.5,
      amp_release_ms: 300,
      pitch_env_amount_oct: 0,
      pitch_env_attack_ms: 0,
      pitch_env_decay_ms: 50,
      lfo_rate_hz: 3,
      lfo_depth: 0.0,
      lfo_shape: 'sine',
      lfo_target: 'off',
      gain: 0.7,
    },
    ranges: {
      base_pitch_semitones: [-6, 6],
      osc_a_level: [0.0, 0.2],
      osc_b_level: [0.0, 0.1],
      noise_type: ['white', 'pink', 'brown'],
      noise_amount: [0.7, 1.0],
      filter_freq_hz: [500, 3500],
      filter_q: [3, 12],
      filter_env_amount: [0.3, 0.9],
      filter_env_attack_ms: [30, 200],
      filter_env_decay_ms: [150, 500],
      amp_attack_ms: [20, 150],
      amp_decay_ms: [50, 200],
      amp_sustain: [0.3, 0.8],
      amp_release_ms: [150, 500],
      lfo_target: ['off', 'filter'],
      lfo_rate_hz: [0.5, 6],
      lfo_depth: [0.0, 0.4],
      gain: [0.6, 0.85],
    },
  },

  magic: {
    key: 'magic',
    name: 'Magic',
    description: 'Ascending sparkly tone — relies on Pattern feature for the arpeggio.',
    defaults: {
      base_pitch_semitones: 0,
      osc_a_wave: 'sine',
      osc_a_level: 0.7,
      osc_b_wave: 'triangle',
      osc_b_level: 0.5,
      osc_b_detune_cents: 12,
      sub_amount: 0.1,
      noise_type: 'none',
      noise_amount: 0.0,
      filter_type: 'lowpass',
      filter_freq_hz: 4500,
      filter_q: 3,
      filter_env_amount: 0.4,
      filter_env_attack_ms: 50,
      filter_env_decay_ms: 300,
      amp_attack_ms: 15,
      amp_decay_ms: 120,
      amp_sustain: 0.5,
      amp_release_ms: 400,
      pitch_env_amount_oct: 0.3,
      pitch_env_attack_ms: 30,
      pitch_env_decay_ms: 200,
      lfo_rate_hz: 6,
      lfo_depth: 0.15,
      lfo_shape: 'sine',
      lfo_target: 'pitch',
      gain: 0.75,
    },
    ranges: {
      base_pitch_semitones: [-18, 18],
      osc_a_wave: ['sine', 'triangle'],
      osc_a_level: [0.5, 1.0],
      osc_b_wave: ['sine', 'triangle', 'saw'],
      osc_b_level: [0.3, 0.7],
      osc_b_detune_cents: [0, 30],
      sub_amount: [0.0, 0.5],
      filter_type: ['lowpass', 'bandpass', 'highpass'],
      filter_freq_hz: [1500, 10000],
      filter_q: [1, 8],
      filter_env_amount: [-0.2, 0.7],
      filter_env_attack_ms: [10, 150],
      filter_env_decay_ms: [150, 600],
      amp_attack_ms: [3, 50],
      amp_decay_ms: [60, 250],
      amp_sustain: [0.3, 0.8],
      amp_release_ms: [200, 800],
      pitch_env_amount_oct: [-0.3, 0.7],
      pitch_env_attack_ms: [0, 80],
      pitch_env_decay_ms: [80, 400],
      lfo_rate_hz: [2, 10],
      lfo_depth: [0.0, 0.4],
      lfo_shape: ['sine', 'triangle'],
      lfo_target: ['off', 'pitch', 'filter'],
      gain: [0.65, 0.85],
    },
  },

  electric: {
    key: 'electric',
    name: 'Electric',
    description: 'Harsh modern synth — dual saw+square, sub, high-Q BP. Canary preset.',
    defaults: {
      base_pitch_semitones: 0,
      osc_a_wave: 'saw',
      osc_a_level: 1.0,
      osc_b_wave: 'square',
      osc_b_level: 0.7,
      osc_b_detune_cents: 18,
      sub_amount: 0.4,
      noise_type: 'white',
      noise_amount: 0.15,
      filter_type: 'bandpass',
      filter_freq_hz: 1800,
      filter_q: 8,
      filter_env_amount: 0.3,
      filter_env_attack_ms: 8,
      filter_env_decay_ms: 120,
      amp_attack_ms: 3,
      amp_decay_ms: 80,
      amp_sustain: 0.4,
      amp_release_ms: 200,
      pitch_env_amount_oct: -0.2,
      pitch_env_attack_ms: 5,
      pitch_env_decay_ms: 80,
      lfo_rate_hz: 7,
      lfo_depth: 0.2,
      lfo_shape: 'triangle',
      lfo_target: 'filter',
      gain: 0.85,
    },
    ranges: {
      base_pitch_semitones: [-12, 12],
      osc_a_wave: ['square', 'saw'],
      osc_a_level: [0.8, 1.0],
      osc_b_wave: ['square', 'saw'],
      osc_b_level: [0.5, 0.9],
      osc_b_detune_cents: [8, 35],
      sub_amount: [0.2, 0.6],
      noise_amount: [0.05, 0.3],
      filter_type: ['bandpass', 'highpass'],
      filter_freq_hz: [800, 4000],
      filter_q: [4, 14],
      filter_env_amount: [-0.3, 0.6],
      filter_env_attack_ms: [0, 30],
      filter_env_decay_ms: [60, 300],
      amp_attack_ms: [0, 10],
      amp_decay_ms: [40, 150],
      amp_sustain: [0.2, 0.7],
      amp_release_ms: [100, 400],
      pitch_env_amount_oct: [-0.5, 0.2],
      pitch_env_attack_ms: [0, 20],
      pitch_env_decay_ms: [40, 200],
      lfo_rate_hz: [3, 14],
      lfo_depth: [0.0, 0.5],
      lfo_shape: ['sine', 'triangle', 'square'],
      lfo_target: ['off', 'pitch', 'filter'],
      gain: [0.75, 0.95],
    },
  },
}

export const TONAL_PRESET_ORDER: TonalPresetKey[] = [
  'laser',
  'coin',
  'beep',
  'jump',
  'whoosh',
  'magic',
  'electric',
]
