import type { AtmosphericParams } from './dsp/atmospheric/types'
import type { FXConfig } from './dsp/fx/types'

export type AtmosphericPresetKey =
  | 'wind'
  | 'rain'
  | 'fire'
  | 'ocean'
  | 'drone'
  | 'hum'
  | 'riser'
  | 'sci_fi_ambient'
  | 'glitch'

type RangeFor<T> = [T] extends [number] ? [number, number] : readonly T[]

export interface AtmosphericPresetDefinition {
  key: AtmosphericPresetKey
  name: string
  description: string
  defaults: AtmosphericParams
  ranges: { [K in keyof AtmosphericParams]?: RangeFor<AtmosphericParams[K]> }
  // Optional FX chain shipped with the preset. When absent, selection resets
  // FX to DEFAULT_FX_CONFIG.
  fx?: FXConfig
}

/* ─── 9 atmospheric presets ─────────────────────────────────────────────
 * Defaults are the canonical "off the shelf" sound for each preset; ranges
 * drive randomize/mutate. Categorical variation matrix follows the spec.
 *
 * Per-preset tuning expectations live in SFX_TOOL_V3_SPEC.md "Atmospheric
 * presets" section; ~50 randomized samples per preset is the validation pass
 * during phase 1.
 */
export const ATMOSPHERIC_PRESETS: Record<
  AtmosphericPresetKey,
  AtmosphericPresetDefinition
> = {
  wind: {
    key: 'wind',
    name: 'Wind',
    description:
      'Gusty, flowing — pink/brown noise with slow random walk on filter cutoff',
    defaults: {
      noise_type: 'pink',
      noise_amount: 0.7,
      osc_count: 0,
      osc_a_wave: 'sine',
      osc_a_level: 0,
      osc_b_wave: 'sine',
      osc_b_level: 0,
      osc_b_detune_cents: 0,
      osc_c_wave: 'sine',
      osc_c_level: 0,
      osc_c_detune_cents: 0,
      base_pitch_semitones: 0,
      filter_a_type: 'bandpass',
      filter_a_freq_hz: 800,
      filter_a_q: 4,
      filter_a_mix: 1,
      filter_b_type: 'bandpass',
      filter_b_freq_hz: 2400,
      filter_b_q: 6,
      filter_b_mix: 0.3,
      slow_env_shape: 'ramp_up',
      slow_env_duration_s: 5,
      slow_env_amount: 0,
      slow_env_target: 'off',
      rw1_rate_hz: 0.7,
      rw1_depth: 0.75,
      rw1_smoothing_ms: 600,
      rw1_target: 'filter_a_freq',
      rw2_rate_hz: 1.5,
      rw2_depth: 0.4,
      rw2_smoothing_ms: 300,
      rw2_target: 'amp',
      lfo1_rate_hz: 0.3,
      lfo1_depth: 0,
      lfo1_shape: 'sine',
      lfo1_phase_offset_deg: 0,
      lfo1_target: 'off',
      lfo2_rate_hz: 0.3,
      lfo2_depth: 0,
      lfo2_shape: 'sine',
      lfo2_phase_offset_deg: 0,
      lfo2_target: 'off',
      gain: 0.6,
    },
    ranges: {
      noise_type: ['pink', 'brown'],
      noise_amount: [0.5, 1.0],
      filter_a_type: ['bandpass'],
      filter_a_freq_hz: [400, 1500],
      filter_a_q: [2, 6],
      filter_a_mix: [0.7, 1.0],
      filter_b_type: ['bandpass'],
      filter_b_freq_hz: [1500, 4000],
      filter_b_q: [4, 10],
      filter_b_mix: [0, 0.5],
      slow_env_target: ['off'],
      rw1_rate_hz: [0.4, 1.2],
      rw1_depth: [0.6, 0.9],
      rw1_smoothing_ms: [400, 1000],
      rw1_target: ['filter_a_freq'],
      rw2_rate_hz: [1, 3],
      rw2_depth: [0.2, 0.5],
      rw2_smoothing_ms: [200, 500],
      rw2_target: ['amp', 'filter_a_q'],
      gain: [0.5, 0.7],
    },
  },

  rain: {
    key: 'rain',
    name: 'Rain',
    description:
      'White/pink noise with HP+BP filters — pattering density without big gusts',
    defaults: {
      noise_type: 'white',
      noise_amount: 0.5,
      osc_count: 0,
      osc_a_wave: 'sine',
      osc_a_level: 0,
      osc_b_wave: 'sine',
      osc_b_level: 0,
      osc_b_detune_cents: 0,
      osc_c_wave: 'sine',
      osc_c_level: 0,
      osc_c_detune_cents: 0,
      base_pitch_semitones: 0,
      filter_a_type: 'lowpass',
      filter_a_freq_hz: 3000,
      filter_a_q: 1,
      filter_a_mix: 1,
      filter_b_type: 'highpass',
      filter_b_freq_hz: 5000,
      filter_b_q: 1,
      filter_b_mix: 0.4,
      slow_env_shape: 'ramp_up',
      slow_env_duration_s: 5,
      slow_env_amount: 0,
      slow_env_target: 'off',
      rw1_rate_hz: 4,
      rw1_depth: 0.3,
      rw1_smoothing_ms: 80,
      rw1_target: 'amp',
      rw2_rate_hz: 6,
      rw2_depth: 0.4,
      rw2_smoothing_ms: 60,
      rw2_target: 'filter_a_freq',
      lfo1_rate_hz: 0.3,
      lfo1_depth: 0,
      lfo1_shape: 'sine',
      lfo1_phase_offset_deg: 0,
      lfo1_target: 'off',
      lfo2_rate_hz: 0.3,
      lfo2_depth: 0,
      lfo2_shape: 'sine',
      lfo2_phase_offset_deg: 0,
      lfo2_target: 'off',
      gain: 0.55,
    },
    ranges: {
      noise_type: ['white', 'pink'],
      noise_amount: [0.4, 0.7],
      filter_a_type: ['lowpass', 'bandpass'],
      filter_a_freq_hz: [2000, 5000],
      filter_b_type: ['highpass'],
      filter_b_freq_hz: [3000, 8000],
      filter_b_mix: [0, 0.6],
      slow_env_target: ['off'],
      rw1_rate_hz: [3, 6],
      rw1_depth: [0.2, 0.5],
      rw1_smoothing_ms: [50, 150],
      rw2_rate_hz: [4, 8],
      rw2_depth: [0.3, 0.6],
      rw2_smoothing_ms: [40, 100],
      gain: [0.45, 0.65],
    },
  },

  fire: {
    key: 'fire',
    name: 'Fire',
    description:
      'Crackling — pink/brown with slow + fast random walks for irregular intensity',
    defaults: {
      noise_type: 'pink',
      noise_amount: 0.65,
      osc_count: 0,
      osc_a_wave: 'sine',
      osc_a_level: 0,
      osc_b_wave: 'sine',
      osc_b_level: 0,
      osc_b_detune_cents: 0,
      osc_c_wave: 'sine',
      osc_c_level: 0,
      osc_c_detune_cents: 0,
      base_pitch_semitones: 0,
      filter_a_type: 'bandpass',
      filter_a_freq_hz: 1500,
      filter_a_q: 8,
      filter_a_mix: 1,
      filter_b_type: 'highpass',
      filter_b_freq_hz: 4000,
      filter_b_q: 2,
      filter_b_mix: 0.25,
      slow_env_shape: 'ramp_up',
      slow_env_duration_s: 5,
      slow_env_amount: 0,
      slow_env_target: 'off',
      rw1_rate_hz: 0.5,
      rw1_depth: 0.6,
      rw1_smoothing_ms: 800,
      rw1_target: 'amp',
      rw2_rate_hz: 5,
      rw2_depth: 0.5,
      rw2_smoothing_ms: 80,
      rw2_target: 'filter_a_freq',
      lfo1_rate_hz: 0.3,
      lfo1_depth: 0,
      lfo1_shape: 'sine',
      lfo1_phase_offset_deg: 0,
      lfo1_target: 'off',
      lfo2_rate_hz: 0.3,
      lfo2_depth: 0,
      lfo2_shape: 'sine',
      lfo2_phase_offset_deg: 0,
      lfo2_target: 'off',
      gain: 0.55,
    },
    ranges: {
      noise_type: ['pink', 'brown'],
      noise_amount: [0.5, 0.8],
      filter_a_type: ['bandpass'],
      filter_a_freq_hz: [800, 2500],
      filter_a_q: [5, 12],
      filter_b_type: ['highpass'],
      filter_b_mix: [0, 0.4],
      slow_env_target: ['off'],
      rw1_rate_hz: [0.3, 0.8],
      rw1_depth: [0.5, 0.8],
      rw1_smoothing_ms: [600, 1200],
      rw2_rate_hz: [3, 8],
      rw2_depth: [0.3, 0.7],
      rw2_smoothing_ms: [50, 150],
      gain: [0.45, 0.65],
    },
  },

  ocean: {
    key: 'ocean',
    name: 'Ocean',
    description:
      'Brown noise with very slow LFO on filter — wave rhythm with irregular Q',
    defaults: {
      noise_type: 'brown',
      noise_amount: 0.85,
      osc_count: 0,
      osc_a_wave: 'sine',
      osc_a_level: 0,
      osc_b_wave: 'sine',
      osc_b_level: 0,
      osc_b_detune_cents: 0,
      osc_c_wave: 'sine',
      osc_c_level: 0,
      osc_c_detune_cents: 0,
      base_pitch_semitones: 0,
      filter_a_type: 'lowpass',
      filter_a_freq_hz: 400,
      filter_a_q: 3,
      filter_a_mix: 1,
      filter_b_type: 'lowpass',
      filter_b_freq_hz: 200,
      filter_b_q: 2,
      filter_b_mix: 0.4,
      slow_env_shape: 'ramp_up',
      slow_env_duration_s: 5,
      slow_env_amount: 0,
      slow_env_target: 'off',
      rw1_rate_hz: 0.4,
      rw1_depth: 0.3,
      rw1_smoothing_ms: 1200,
      rw1_target: 'filter_a_q',
      rw2_rate_hz: 0.2,
      rw2_depth: 0,
      rw2_smoothing_ms: 1000,
      rw2_target: 'off',
      lfo1_rate_hz: 0.18,
      lfo1_depth: 0.5,
      lfo1_shape: 'sine',
      lfo1_phase_offset_deg: 0,
      lfo1_target: 'filter_a_freq',
      lfo2_rate_hz: 0.3,
      lfo2_depth: 0,
      lfo2_shape: 'sine',
      lfo2_phase_offset_deg: 0,
      lfo2_target: 'off',
      gain: 0.6,
    },
    ranges: {
      noise_type: ['brown'],
      noise_amount: [0.7, 1.0],
      filter_a_type: ['lowpass'],
      filter_a_freq_hz: [200, 700],
      filter_b_type: ['lowpass', 'bandpass'],
      filter_b_mix: [0, 0.5],
      slow_env_target: ['off'],
      rw1_rate_hz: [0.2, 0.6],
      rw1_depth: [0.2, 0.5],
      rw1_target: ['filter_a_q', 'filter_a_freq'],
      lfo1_rate_hz: [0.1, 0.3],
      lfo1_depth: [0.3, 0.7],
      lfo1_target: ['filter_a_freq'],
      gain: [0.5, 0.7],
    },
  },

  drone: {
    key: 'drone',
    name: 'Drone',
    description:
      'Pitched: 1-3 oscillators + light noise, slow RW filter, optional shimmer',
    defaults: {
      noise_type: 'pink',
      noise_amount: 0.15,
      osc_count: 2,
      osc_a_wave: 'sine',
      osc_a_level: 0.7,
      osc_b_wave: 'triangle',
      osc_b_level: 0.5,
      osc_b_detune_cents: 7,
      osc_c_wave: 'sine',
      osc_c_level: 0.4,
      osc_c_detune_cents: 12,
      base_pitch_semitones: -12,
      filter_a_type: 'lowpass',
      filter_a_freq_hz: 1500,
      filter_a_q: 2,
      filter_a_mix: 1,
      filter_b_type: 'lowpass',
      filter_b_freq_hz: 600,
      filter_b_q: 1.5,
      filter_b_mix: 0.3,
      slow_env_shape: 'ramp_up',
      slow_env_duration_s: 5,
      slow_env_amount: 0,
      slow_env_target: 'off',
      rw1_rate_hz: 0.3,
      rw1_depth: 0.5,
      rw1_smoothing_ms: 1500,
      rw1_target: 'filter_a_freq',
      rw2_rate_hz: 0.5,
      rw2_depth: 0,
      rw2_smoothing_ms: 800,
      rw2_target: 'off',
      lfo1_rate_hz: 5,
      lfo1_depth: 0.15,
      lfo1_shape: 'sine',
      lfo1_phase_offset_deg: 0,
      lfo1_target: 'pitch',
      lfo2_rate_hz: 0.3,
      lfo2_depth: 0,
      lfo2_shape: 'sine',
      lfo2_phase_offset_deg: 0,
      lfo2_target: 'off',
      gain: 0.55,
    },
    ranges: {
      noise_type: ['off', 'pink'],
      noise_amount: [0, 0.3],
      osc_count: [1, 3],
      osc_a_level: [0.5, 0.9],
      osc_b_level: [0.3, 0.7],
      osc_b_detune_cents: [3, 14],
      osc_c_level: [0.2, 0.6],
      osc_c_detune_cents: [5, 20],
      base_pitch_semitones: [-24, -6],
      filter_a_type: ['lowpass', 'bandpass'],
      filter_a_freq_hz: [800, 2500],
      filter_b_mix: [0, 0.5],
      slow_env_target: ['off', 'amp'],
      rw1_rate_hz: [0.15, 0.5],
      rw1_depth: [0.3, 0.7],
      rw1_smoothing_ms: [1000, 2000],
      lfo1_rate_hz: [4, 7],
      lfo1_depth: [0.05, 0.25],
      lfo1_target: ['pitch', 'off'],
      gain: [0.5, 0.7],
    },
  },

  hum: {
    key: 'hum',
    name: 'Hum',
    description:
      'Mechanical low-frequency — sine/triangle pitched low, periodic LFO on Q',
    defaults: {
      noise_type: 'off',
      noise_amount: 0,
      osc_count: 2,
      osc_a_wave: 'sine',
      osc_a_level: 0.85,
      osc_b_wave: 'sine',
      osc_b_level: 0.5,
      osc_b_detune_cents: 4,
      osc_c_wave: 'triangle',
      osc_c_level: 0.3,
      osc_c_detune_cents: 0,
      base_pitch_semitones: -18,
      filter_a_type: 'lowpass',
      filter_a_freq_hz: 800,
      filter_a_q: 4,
      filter_a_mix: 1,
      filter_b_type: 'lowpass',
      filter_b_freq_hz: 200,
      filter_b_q: 2,
      filter_b_mix: 0,
      slow_env_shape: 'ramp_up',
      slow_env_duration_s: 5,
      slow_env_amount: 0,
      slow_env_target: 'off',
      rw1_rate_hz: 0.5,
      rw1_depth: 0,
      rw1_smoothing_ms: 600,
      rw1_target: 'off',
      rw2_rate_hz: 0.5,
      rw2_depth: 0,
      rw2_smoothing_ms: 600,
      rw2_target: 'off',
      lfo1_rate_hz: 2.5,
      lfo1_depth: 0.5,
      lfo1_shape: 'sine',
      lfo1_phase_offset_deg: 0,
      lfo1_target: 'filter_a_q',
      lfo2_rate_hz: 0.4,
      lfo2_depth: 0.2,
      lfo2_shape: 'triangle',
      lfo2_phase_offset_deg: 90,
      lfo2_target: 'amp',
      gain: 0.55,
    },
    ranges: {
      noise_type: ['off', 'brown'],
      noise_amount: [0, 0.2],
      osc_count: [1, 2],
      osc_a_level: [0.6, 1.0],
      osc_b_level: [0.3, 0.7],
      osc_b_detune_cents: [2, 10],
      base_pitch_semitones: [-24, -12],
      filter_a_type: ['lowpass'],
      filter_a_freq_hz: [400, 1500],
      filter_b_mix: [0, 0.4],
      slow_env_target: ['off', 'amp'],
      lfo1_rate_hz: [1, 5],
      lfo1_depth: [0.3, 0.7],
      lfo1_target: ['filter_a_q', 'amp'],
      lfo2_rate_hz: [0.2, 0.8],
      lfo2_depth: [0.1, 0.4],
      gain: [0.5, 0.7],
    },
  },

  riser: {
    key: 'riser',
    name: 'Riser',
    description:
      'Building intensity — slow envelope on amp + filter for game tension',
    defaults: {
      noise_type: 'pink',
      noise_amount: 0.7,
      osc_count: 1,
      osc_a_wave: 'triangle',
      osc_a_level: 0.4,
      osc_b_wave: 'sine',
      osc_b_level: 0,
      osc_b_detune_cents: 0,
      osc_c_wave: 'sine',
      osc_c_level: 0,
      osc_c_detune_cents: 0,
      base_pitch_semitones: -6,
      filter_a_type: 'bandpass',
      filter_a_freq_hz: 600,
      filter_a_q: 3,
      filter_a_mix: 1,
      filter_b_type: 'bandpass',
      filter_b_freq_hz: 2000,
      filter_b_q: 4,
      filter_b_mix: 0.4,
      slow_env_shape: 'ramp_up',
      slow_env_duration_s: 6,
      slow_env_amount: 1,
      slow_env_target: 'amp',
      rw1_rate_hz: 1,
      rw1_depth: 0.4,
      rw1_smoothing_ms: 400,
      rw1_target: 'filter_a_freq',
      rw2_rate_hz: 0.5,
      rw2_depth: 0,
      rw2_smoothing_ms: 600,
      rw2_target: 'off',
      lfo1_rate_hz: 0.3,
      lfo1_depth: 0,
      lfo1_shape: 'sine',
      lfo1_phase_offset_deg: 0,
      lfo1_target: 'off',
      lfo2_rate_hz: 0.3,
      lfo2_depth: 0,
      lfo2_shape: 'sine',
      lfo2_phase_offset_deg: 0,
      lfo2_target: 'off',
      gain: 0.6,
    },
    ranges: {
      noise_type: ['pink', 'brown', 'white'],
      noise_amount: [0.5, 0.85],
      osc_count: [0, 2],
      osc_a_level: [0.3, 0.6],
      base_pitch_semitones: [-12, 0],
      filter_a_type: ['bandpass'],
      filter_a_freq_hz: [400, 900],
      filter_a_q: [2, 5],
      filter_b_mix: [0, 0.6],
      slow_env_shape: ['ramp_up', 'attack_hold_release'],
      slow_env_duration_s: [4, 10],
      slow_env_amount: [0.7, 1],
      slow_env_target: ['amp'],
      rw1_rate_hz: [0.5, 1.5],
      rw1_depth: [0.2, 0.6],
      gain: [0.5, 0.7],
    },
  },

  sci_fi_ambient: {
    key: 'sci_fi_ambient',
    name: 'Sci-fi Ambient',
    description:
      'Drone + shimmer — fast LFO/RW on a HP filter for alien atmosphere',
    defaults: {
      noise_type: 'blue',
      noise_amount: 0.35,
      osc_count: 2,
      osc_a_wave: 'sine',
      osc_a_level: 0.5,
      osc_b_wave: 'triangle',
      osc_b_level: 0.4,
      osc_b_detune_cents: 17,
      osc_c_wave: 'sine',
      osc_c_level: 0,
      osc_c_detune_cents: 0,
      base_pitch_semitones: -7,
      filter_a_type: 'bandpass',
      filter_a_freq_hz: 1200,
      filter_a_q: 4,
      filter_a_mix: 0.7,
      filter_b_type: 'highpass',
      filter_b_freq_hz: 4000,
      filter_b_q: 2,
      filter_b_mix: 0.5,
      slow_env_shape: 'attack_hold_release',
      slow_env_duration_s: 8,
      slow_env_amount: 0.3,
      slow_env_target: 'amp',
      rw1_rate_hz: 0.4,
      rw1_depth: 0.5,
      rw1_smoothing_ms: 800,
      rw1_target: 'filter_a_freq',
      rw2_rate_hz: 3,
      rw2_depth: 0.4,
      rw2_smoothing_ms: 100,
      rw2_target: 'filter_b_freq',
      lfo1_rate_hz: 0.7,
      lfo1_depth: 0.25,
      lfo1_shape: 'triangle',
      lfo1_phase_offset_deg: 0,
      lfo1_target: 'pitch',
      lfo2_rate_hz: 0.3,
      lfo2_depth: 0,
      lfo2_shape: 'sine',
      lfo2_phase_offset_deg: 0,
      lfo2_target: 'off',
      gain: 0.55,
    },
    ranges: {
      noise_type: ['white', 'pink', 'blue'],
      noise_amount: [0.2, 0.5],
      osc_count: [0, 3],
      osc_a_level: [0.3, 0.7],
      osc_b_level: [0.2, 0.6],
      osc_b_detune_cents: [10, 30],
      base_pitch_semitones: [-12, 0],
      filter_a_type: ['lowpass', 'bandpass'],
      filter_b_type: ['highpass'],
      filter_b_freq_hz: [3000, 7000],
      slow_env_target: ['off', 'amp'],
      rw1_rate_hz: [0.2, 0.7],
      rw2_rate_hz: [2, 5],
      lfo1_rate_hz: [0.4, 1.5],
      lfo1_depth: [0.1, 0.4],
      gain: [0.5, 0.65],
    },
  },

  glitch: {
    key: 'glitch',
    name: 'Glitch',
    description:
      'Wildcard — fast RWs at high depth, broken-electronic feel',
    defaults: {
      noise_type: 'white',
      noise_amount: 0.5,
      osc_count: 2,
      osc_a_wave: 'sine',
      osc_a_level: 0.6,
      osc_b_wave: 'triangle',
      osc_b_level: 0.5,
      osc_b_detune_cents: 33,
      osc_c_wave: 'sine',
      osc_c_level: 0,
      osc_c_detune_cents: 0,
      base_pitch_semitones: 0,
      filter_a_type: 'bandpass',
      filter_a_freq_hz: 2000,
      filter_a_q: 8,
      filter_a_mix: 1,
      filter_b_type: 'highpass',
      filter_b_freq_hz: 3000,
      filter_b_q: 6,
      filter_b_mix: 0.6,
      slow_env_shape: 'ramp_up',
      slow_env_duration_s: 5,
      slow_env_amount: 0,
      slow_env_target: 'off',
      rw1_rate_hz: 6,
      rw1_depth: 0.8,
      rw1_smoothing_ms: 80,
      rw1_target: 'filter_a_freq',
      rw2_rate_hz: 8,
      rw2_depth: 0.7,
      rw2_smoothing_ms: 60,
      rw2_target: 'pitch',
      lfo1_rate_hz: 12,
      lfo1_depth: 0.4,
      lfo1_shape: 'square',
      lfo1_phase_offset_deg: 0,
      lfo1_target: 'amp',
      lfo2_rate_hz: 0.3,
      lfo2_depth: 0,
      lfo2_shape: 'sine',
      lfo2_phase_offset_deg: 0,
      lfo2_target: 'off',
      gain: 0.55,
    },
    ranges: {
      noise_type: ['white', 'pink', 'brown', 'blue', 'violet', 'grey', 'off'],
      noise_amount: [0.2, 0.8],
      osc_count: [0, 3],
      osc_a_level: [0.3, 0.9],
      osc_b_level: [0.2, 0.8],
      osc_b_detune_cents: [0, 50],
      osc_c_level: [0, 0.6],
      osc_c_detune_cents: [0, 50],
      base_pitch_semitones: [-24, 12],
      filter_a_type: ['highpass', 'bandpass', 'lowpass'],
      filter_a_freq_hz: [200, 8000],
      filter_a_q: [3, 15],
      filter_b_type: ['highpass', 'bandpass', 'lowpass'],
      filter_b_freq_hz: [200, 8000],
      filter_b_q: [3, 12],
      slow_env_target: ['off', 'amp', 'filter_a_freq'],
      rw1_rate_hz: [3, 10],
      rw1_depth: [0.5, 1],
      rw2_rate_hz: [3, 10],
      rw2_depth: [0.4, 0.9],
      rw1_target: ['filter_a_freq', 'filter_a_q', 'filter_b_freq', 'pitch', 'amp'],
      rw2_target: ['filter_a_freq', 'filter_a_q', 'filter_b_freq', 'pitch', 'amp'],
      lfo1_rate_hz: [4, 16],
      lfo1_depth: [0.2, 0.6],
      lfo1_shape: ['sine', 'triangle', 'square'],
      lfo1_target: ['amp', 'filter_a_q', 'pitch'],
      gain: [0.45, 0.65],
    },
  },
}

export const ATMOSPHERIC_PRESET_ORDER: AtmosphericPresetKey[] = [
  'wind',
  'rain',
  'fire',
  'ocean',
  'drone',
  'hum',
  'riser',
  'sci_fi_ambient',
  'glitch',
]
