import type { TonalParams } from './dsp/types'
import type { PatternConfig } from './dsp/pattern/types'
import type { FXConfig } from './dsp/fx/types'

export type TonalPresetKey =
  | 'laser'
  | 'coin'
  | 'beep'
  | 'jump'
  | 'whoosh'
  | 'magic'
  | 'electric'

// Same RangeFor pattern as v1's percussive presets — numeric params get
// [min, max], categorical params get readonly arrays. The [T] tuple wrap
// prevents distribution over union types.
type RangeFor<T> = [T] extends [number] ? [number, number] : readonly T[]

export interface TonalPresetDefinition {
  key: TonalPresetKey
  name: string
  description: string
  defaults: TonalParams
  ranges: {
    [K in keyof TonalParams]?: RangeFor<TonalParams[K]>
  }
  // Optional pattern shipped with the preset. When set, selecting this preset
  // also applies this pattern (with `enabled: true`); when absent, selection
  // resets pattern to default.
  pattern?: Omit<PatternConfig, 'enabled'>
  // Optional FX chain shipped with the preset. When absent, selection resets
  // FX to DEFAULT_FX_CONFIG.
  fx?: FXConfig
}

export const TONAL_PRESETS: Record<TonalPresetKey, TonalPresetDefinition> = {
  laser: {
    key: 'laser',
    name: 'Laser',
    description:
      'Pitch-sweep aggressive sound — square+saw with downward sweep. The classic.',
    defaults: {
      base_pitch_semitones: 8,
      osc_a_wave: 'square',
      osc_a_level: 0.89,
      osc_b_wave: 'saw',
      osc_b_level: 0,
      osc_b_detune_cents: 5,
      sub_amount: 0.33,
      noise_type: 'white',
      noise_amount: 0.37,
      filter_type: 'lowpass',
      filter_freq_hz: 1924,
      filter_q: 2.25,
      filter_env_amount: 0.91,
      filter_env_attack_ms: 309,
      filter_env_decay_ms: 6,
      amp_attack_ms: 18,
      amp_decay_ms: 6,
      amp_sustain: 0.81,
      amp_release_ms: 136,
      pitch_env_amount_oct: -1.84,
      pitch_env_attack_ms: 233,
      pitch_env_decay_ms: 9,
      lfo_rate_hz: 5,
      lfo_depth: 0.0,
      lfo_shape: 'sine',
      lfo_target: 'off',
      gain: 0.81,
    },
    ranges: {
      base_pitch_semitones: [-6, 8],
      osc_a_wave: ['square', 'saw'],
      osc_a_level: [0.6, 1.0],
      osc_b_wave: ['square', 'saw', 'sine'],
      osc_b_level: [0.0, 0.8],
      osc_b_detune_cents: [0, 25],
      sub_amount: [0.0, 0.4],
      noise_type: ['white', 'pink'],
      noise_amount: [0.0, 0.4],
      filter_type: ['lowpass', 'bandpass'],
      filter_freq_hz: [1500, 8000],
      filter_q: [2, 8],
      filter_env_amount: [-0.8, 0.95],
      filter_env_attack_ms: [5, 350],
      filter_env_decay_ms: [5, 400],
      amp_attack_ms: [0, 25],
      amp_decay_ms: [5, 200],
      amp_sustain: [0.0, 0.85],
      amp_release_ms: [80, 300],
      pitch_env_amount_oct: [-2.0, -0.8],
      pitch_env_attack_ms: [5, 250],
      pitch_env_decay_ms: [5, 350],
      lfo_target: ['off', 'pitch'],
      lfo_depth: [0.0, 0.3],
      gain: [0.75, 0.95],
    },
    pattern: {
      steps: 1,
      interval_ms: 110,
      pitch_offsets: [0],
      volume_decay: 1,
      direction: 'forward',
    },
  },

  coin: {
    key: 'coin',
    name: 'Coin',
    description: 'Bright pickup with tonal ring — triangle+sine, holds for ring.',
    defaults: {
      base_pitch_semitones: 9,
      osc_a_wave: 'triangle',
      osc_a_level: 0.9,
      osc_b_wave: 'triangle',
      osc_b_level: 0.4,
      osc_b_detune_cents: 0,
      sub_amount: 0.04,
      noise_type: 'none',
      noise_amount: 0.0,
      filter_type: 'lowpass',
      filter_freq_hz: 656,
      filter_q: 0.75,
      filter_env_amount: 0.05,
      filter_env_attack_ms: 23,
      filter_env_decay_ms: 12,
      amp_attack_ms: 9,
      amp_decay_ms: 144,
      amp_sustain: 0.07,
      amp_release_ms: 41,
      pitch_env_amount_oct: -0.02,
      pitch_env_attack_ms: 12,
      pitch_env_decay_ms: 18,
      lfo_rate_hz: 0.15,
      lfo_depth: 0.05,
      lfo_shape: 'square',
      lfo_target: 'off',
      gain: 0.75,
    },
    ranges: {
      base_pitch_semitones: [-12, 12],
      osc_a_wave: ['sine', 'triangle'],
      osc_a_level: [0.7, 1.0],
      osc_b_wave: ['sine', 'triangle'],
      osc_b_level: [0.2, 0.7],
      osc_b_detune_cents: [0, 15],
      sub_amount: [0.0, 0.3],
      filter_freq_hz: [400, 9000],
      filter_q: [0.7, 3],
      filter_env_amount: [-0.2, 0.2],
      filter_env_decay_ms: [10, 200],
      amp_attack_ms: [1, 15],
      amp_decay_ms: [30, 200],
      amp_sustain: [0.05, 0.8],
      amp_release_ms: [30, 450],
      pitch_env_amount_oct: [-0.1, 0.1],
      pitch_env_decay_ms: [15, 100],
      lfo_depth: [0.0, 0.2],
      gain: [0.65, 0.9],
    },
    pattern: {
      steps: 3,
      interval_ms: 74,
      pitch_offsets: [0, 12, 19],
      volume_decay: 0.7,
      direction: 'forward',
    },
  },

  beep: {
    key: 'beep',
    name: 'Beep',
    description: 'Simple UI confirmation — sine, brief, fixed pitch. Minimal preset.',
    defaults: {
      base_pitch_semitones: 0,
      osc_a_wave: 'sine',
      osc_a_level: 1.0,
      osc_b_wave: 'sine',
      osc_b_level: 0.0,
      osc_b_detune_cents: 0,
      sub_amount: 0.0,
      noise_type: 'none',
      noise_amount: 0.0,
      filter_type: 'lowpass',
      filter_freq_hz: 8000,
      filter_q: 0.7,
      filter_env_amount: 0.0,
      filter_env_attack_ms: 0,
      filter_env_decay_ms: 50,
      amp_attack_ms: 3,
      amp_decay_ms: 30,
      amp_sustain: 0.7,
      amp_release_ms: 80,
      pitch_env_amount_oct: 0,
      pitch_env_attack_ms: 0,
      pitch_env_decay_ms: 50,
      lfo_rate_hz: 4,
      lfo_depth: 0.0,
      lfo_shape: 'sine',
      lfo_target: 'off',
      gain: 0.7,
    },
    ranges: {
      base_pitch_semitones: [-12, 12],
      osc_a_wave: ['sine', 'triangle'],
      osc_a_level: [0.8, 1.0],
      osc_b_level: [0.0, 0.2],
      osc_b_detune_cents: [0, 8],
      filter_freq_hz: [5000, 12000],
      filter_q: [0.5, 1.5],
      amp_attack_ms: [1, 8],
      amp_decay_ms: [15, 60],
      amp_sustain: [0.5, 0.9],
      amp_release_ms: [40, 150],
      lfo_depth: [0.0, 0.2],
      gain: [0.6, 0.85],
    },
  },

  jump: {
    key: 'jump',
    name: 'Jump',
    description: 'Upward pitch sweep with quick decay — platformer staple.',
    defaults: {
      base_pitch_semitones: 0,
      osc_a_wave: 'square',
      osc_a_level: 0.9,
      osc_b_wave: 'triangle',
      osc_b_level: 0.4,
      osc_b_detune_cents: 6,
      sub_amount: 0.1,
      noise_type: 'none',
      noise_amount: 0.0,
      filter_type: 'lowpass',
      filter_freq_hz: 5500,
      filter_q: 2,
      filter_env_amount: 0.2,
      filter_env_attack_ms: 5,
      filter_env_decay_ms: 150,
      amp_attack_ms: 4,
      amp_decay_ms: 80,
      amp_sustain: 0.0,
      amp_release_ms: 150,
      pitch_env_amount_oct: 1.2,
      pitch_env_attack_ms: 80,
      pitch_env_decay_ms: 100,
      lfo_rate_hz: 4,
      lfo_depth: 0.0,
      lfo_shape: 'sine',
      lfo_target: 'off',
      gain: 0.8,
    },
    ranges: {
      base_pitch_semitones: [-6, 6],
      osc_a_wave: ['square', 'triangle'],
      osc_a_level: [0.7, 1.0],
      osc_b_wave: ['square', 'triangle'],
      osc_b_level: [0.2, 0.6],
      osc_b_detune_cents: [0, 18],
      sub_amount: [0.0, 0.4],
      filter_type: ['lowpass', 'bandpass'],
      filter_freq_hz: [3000, 9000],
      filter_q: [1, 4],
      filter_env_amount: [-0.2, 0.5],
      filter_env_attack_ms: [0, 20],
      filter_env_decay_ms: [80, 250],
      amp_attack_ms: [1, 12],
      amp_decay_ms: [40, 150],
      amp_sustain: [0.0, 0.3],
      amp_release_ms: [80, 280],
      pitch_env_amount_oct: [0.6, 1.8],
      pitch_env_attack_ms: [40, 150],
      pitch_env_decay_ms: [50, 200],
      lfo_depth: [0.0, 0.2],
      gain: [0.7, 0.9],
    },
  },

  whoosh: {
    key: 'whoosh',
    name: 'Whoosh',
    description: 'Noise-dominated swept sound — BP filter sweep on noise.',
    defaults: {
      base_pitch_semitones: 0,
      osc_a_wave: 'sine',
      osc_a_level: 0.02,
      osc_b_wave: 'triangle',
      osc_b_level: 0,
      osc_b_detune_cents: 0,
      sub_amount: 0.07,
      noise_type: 'brown',
      noise_amount: 0.4,
      filter_type: 'bandpass',
      filter_freq_hz: 391,
      filter_q: 1.7,
      filter_env_amount: 0.46,
      filter_env_attack_ms: 54,
      filter_env_decay_ms: 628,
      amp_attack_ms: 49,
      amp_decay_ms: 100,
      amp_sustain: 0.39,
      amp_release_ms: 1087,
      pitch_env_amount_oct: -0.17,
      pitch_env_attack_ms: 72,
      pitch_env_decay_ms: 50,
      lfo_rate_hz: 3,
      lfo_depth: 0.27,
      lfo_shape: 'sine',
      lfo_target: 'off',
      gain: 0.94,
    },
    ranges: {
      base_pitch_semitones: [-6, 6],
      osc_a_level: [0.0, 0.2],
      osc_b_level: [0.0, 0.1],
      noise_type: ['white', 'pink', 'brown'],
      noise_amount: [0.3, 1.0],
      filter_freq_hz: [350, 3500],
      filter_q: [1.5, 12],
      filter_env_amount: [0.3, 0.9],
      filter_env_attack_ms: [30, 200],
      filter_env_decay_ms: [150, 700],
      amp_attack_ms: [20, 150],
      amp_decay_ms: [50, 200],
      amp_sustain: [0.3, 0.8],
      amp_release_ms: [150, 1200],
      lfo_target: ['off', 'filter'],
      lfo_rate_hz: [0.5, 6],
      lfo_depth: [0.0, 0.4],
      gain: [0.6, 0.95],
    },
    pattern: {
      steps: 1,
      interval_ms: 34,
      pitch_offsets: [0],
      volume_decay: 0.11,
      direction: 'forward',
    },
  },

  magic: {
    key: 'magic',
    name: 'Magic',
    description: 'Ascending sparkly tone — relies on Pattern feature for the arpeggio.',
    defaults: {
      base_pitch_semitones: -9,
      osc_a_wave: 'sine',
      osc_a_level: 0.9,
      osc_b_wave: 'sine',
      osc_b_level: 0.51,
      osc_b_detune_cents: 43,
      sub_amount: 0.42,
      noise_type: 'brown',
      noise_amount: 0.32,
      filter_type: 'lowpass',
      filter_freq_hz: 3251,
      filter_q: 1.53,
      filter_env_amount: -0.89,
      filter_env_attack_ms: 99,
      filter_env_decay_ms: 8,
      amp_attack_ms: 36,
      amp_decay_ms: 218,
      amp_sustain: 0.76,
      amp_release_ms: 588,
      pitch_env_amount_oct: -0.22,
      pitch_env_attack_ms: 41,
      pitch_env_decay_ms: 105,
      lfo_rate_hz: 4.25,
      lfo_depth: 0.03,
      lfo_shape: 'sine',
      lfo_target: 'filter',
      gain: 0.67,
    },
    ranges: {
      base_pitch_semitones: [-18, 18],
      osc_a_wave: ['sine', 'triangle'],
      osc_a_level: [0.5, 1.0],
      osc_b_wave: ['sine', 'triangle', 'saw'],
      osc_b_level: [0.3, 0.7],
      osc_b_detune_cents: [0, 50],
      sub_amount: [0.0, 0.5],
      filter_type: ['lowpass', 'bandpass', 'highpass'],
      filter_freq_hz: [1500, 10000],
      filter_q: [1, 8],
      filter_env_amount: [-0.95, 0.7],
      filter_env_attack_ms: [10, 150],
      filter_env_decay_ms: [5, 600],
      amp_attack_ms: [3, 50],
      amp_decay_ms: [60, 250],
      amp_sustain: [0.3, 0.8],
      amp_release_ms: [200, 800],
      pitch_env_amount_oct: [-0.3, 0.7],
      pitch_env_attack_ms: [0, 80],
      pitch_env_decay_ms: [80, 400],
      lfo_rate_hz: [2, 10],
      lfo_depth: [0.0, 0.4],
      lfo_shape: ['sine', 'triangle'],
      lfo_target: ['off', 'pitch', 'filter'],
      gain: [0.6, 0.85],
    },
    pattern: {
      steps: 8,
      interval_ms: 193,
      pitch_offsets: [0, 0, 0, 0, 0, 0, 0, 0],
      volume_decay: 0.6,
      direction: 'forward',
    },
  },

  electric: {
    key: 'electric',
    name: 'Electric',
    description: 'Harsh modern synth — dual saw+square, sub, high-Q BP. Canary preset.',
    defaults: {
      base_pitch_semitones: -22,
      osc_a_wave: 'saw',
      osc_a_level: 0.96,
      osc_b_wave: 'saw',
      osc_b_level: 0.36,
      osc_b_detune_cents: 50,
      sub_amount: 0.3,
      noise_type: 'pink',
      noise_amount: 0.26,
      filter_type: 'bandpass',
      filter_freq_hz: 6947,
      filter_q: 1.4,
      filter_env_amount: -0.51,
      filter_env_attack_ms: 357,
      filter_env_decay_ms: 59,
      amp_attack_ms: 484,
      amp_decay_ms: 38,
      amp_sustain: 0.58,
      amp_release_ms: 24,
      pitch_env_amount_oct: -1.86,
      pitch_env_attack_ms: 119,
      pitch_env_decay_ms: 11,
      lfo_rate_hz: 18.1,
      lfo_depth: 0.99,
      lfo_shape: 'sine',
      lfo_target: 'amp',
      gain: 0.89,
    },
    ranges: {
      base_pitch_semitones: [-24, 12],
      osc_a_wave: ['square', 'saw'],
      osc_a_level: [0.8, 1.0],
      osc_b_wave: ['square', 'saw'],
      osc_b_level: [0.3, 0.9],
      osc_b_detune_cents: [8, 50],
      sub_amount: [0.2, 0.6],
      noise_amount: [0.05, 0.3],
      filter_type: ['bandpass', 'highpass'],
      filter_freq_hz: [800, 7500],
      filter_q: [1.2, 14],
      filter_env_amount: [-0.6, 0.6],
      filter_env_attack_ms: [0, 400],
      filter_env_decay_ms: [50, 300],
      amp_attack_ms: [0, 500],
      amp_decay_ms: [30, 150],
      amp_sustain: [0.2, 0.7],
      amp_release_ms: [20, 400],
      pitch_env_amount_oct: [-2.0, 0.2],
      pitch_env_attack_ms: [0, 130],
      pitch_env_decay_ms: [10, 200],
      lfo_rate_hz: [3, 20],
      lfo_depth: [0.0, 1.0],
      lfo_shape: ['sine', 'triangle', 'square'],
      lfo_target: ['off', 'pitch', 'filter', 'amp'],
      gain: [0.75, 0.95],
    },
    pattern: {
      steps: 1,
      interval_ms: 34,
      pitch_offsets: [0],
      volume_decay: 0.11,
      direction: 'forward',
    },
  },
}

export const TONAL_PRESET_ORDER: TonalPresetKey[] = [
  'laser',
  'coin',
  'beep',
  'jump',
  'whoosh',
  'magic',
  'electric',
]
